services:
  - type: web
    name: asistcontrol
    runtime: docker
    region: oregon
    plan: free
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://ep-icy-cake-adeo8hh0-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_SNiG4X6sFjpH


